### ISSUE TITLE
Update tscfg dependency to 0.9.3

### ISSUE THREAD

**Issue by bhchandra** [timvlaer/tscfg-maven-plugin#1]
The latest tscfg version has an option to generate getters. 
It would be great if you update the plugin to support the latest version of tscfg.

**Comment by timvlaer** [comment]
Hi @bhchandra 
Thanks for the suggestion, give me some time to upgrade tscfg and the option to generate getters. Hope to find some time later this week.
(Or feel free to open a PR :-) )
Regards,
Tim

**Comment by bhchandra** [comment]
Ok. I'll submit a PR.

**Comment by timvlaer** [comment]
I prepared the code on the develop branch (see PR #2). I will release it later today to the central repo. 

If you like, you can already test it by checking out the develop branch, do a `mvn install` and depend on `com.github.timvlaer:tscfg-maven-plugin:0.3.0-SNAPSHOT`

**Comment by timvlaer** [comment]
Released to central repo, should be available in a couple of minutes.
https://github.com/timvlaer/tscfg-maven-plugin/releases/tag/0.3.0

**Comment by bhchandra** [comment]
Thank you.
