### ISSUE TITLE
tscfg 0.9.9 released

### ISSUE THREAD

**Issue by carueda** [timvlaer/tscfg-maven-plugin#3]
FYI @timvlaer 

- https://search.maven.org/artifact/com.github.carueda/tscfg_2.12/0.9.9/jar
- https://github.com/carueda/tscfg/releases/tag/v0.9.9

cheers -c

**Comment by timvlaer** [comment]
Thanks for notifying! I'll update the plug-in soon.
( And add options for `Optional` and `Duration` support)

**Comment by timvlaer** [comment]
The integration test caused a bit of lag, but version 0.6.0 of the plugin is out. 
See https://github.com/timvlaer/tscfg-maven-plugin/releases/tag/0.6.0

**Comment by carueda** [comment]
Hi again @timvlaer

FYI  tscfg 0.9.91 released, https://github.com/carueda/tscfg/releases/tag/v0.9.91.  I just pushed the release to maven central but not sure how long it'll take to get reflected there.

(BTW, I just thought I'd add a comment here instead of creating a new issue, but feel free to tell me how you would prefer to get notified ... hmm, actually you may want use the "watch for releases" feature in github ; )  --cheers. -c

**Comment by timvlaer** [comment]
Hi @carueda, thans again for notifying me. I enabled the ‘watch releases’ option, but apparently i forgot to enable the e-mail notification. Anyways, reacting to this issue is perfectly fine. I’ll do the necessary actions to upgrade the maven plug-in.

**Comment by timvlaer** [comment]
For the record: v0.7.0 of this plugin is released.
